-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_sectores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_sectores` (
  `PF_EMP_SEC_EMPRESA` INT(11) NOT NULL,
  `PK_SEC_CODIGO_SECTOR` INT(11) NOT NULL,
  `SEC_NOMBRE_SECTOR` VARCHAR(50) NOT NULL,
  `SEC_DIAS_CARTERA` INT(11) NOT NULL,
  `SEC_CUENTA` VARCHAR(12) NOT NULL,
  `SEC_CUENTA_CXC` VARCHAR(12) NOT NULL,
  `SEC_CUENTA_IVA` VARCHAR(12) NOT NULL,
  `SEC_CUENTA_DEV` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`PF_EMP_SEC_EMPRESA`, `PK_SEC_CODIGO_SECTOR`),
  CONSTRAINT `FK_EMPRESA_SECTORES`
    FOREIGN KEY (`PF_EMP_SEC_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_actividad_economica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_actividad_economica` (
  `PF_EMP_ACE_EMPRESA` INT(11) NOT NULL,
  `PK_ACE_CODIGO_ACTIVIDAD` INT(11) NOT NULL,
  `FK_SEC_ACE_SECTOR` INT(11) NOT NULL,
  `FK_CEN_ACE_CENTRO_COSTO` VARCHAR(10) NULL DEFAULT NULL,
  `FK_CEN_ACE_SUB_CENTRO_COSTO` VARCHAR(10) NULL DEFAULT NULL,
  `ACE_NOMBRE_ACTIVIDAD` VARCHAR(30) NULL DEFAULT NULL,
  `ACE_DIAS_RECAUDO` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_ACE_CODIGO_ACTIVIDAD`, `PF_EMP_ACE_EMPRESA`),
  INDEX `fk_INV_ACTIVIDAD_ECONOMICA_INV_SECTORES1_idx` (`PF_EMP_ACE_EMPRESA` ASC, `FK_SEC_ACE_SECTOR` ASC),
  INDEX `FK_CENTROSCOS_ACT_ECON` (`PF_EMP_ACE_EMPRESA` ASC, `FK_CEN_ACE_CENTRO_COSTO` ASC, `FK_CEN_ACE_SUB_CENTRO_COSTO` ASC),
  CONSTRAINT `FK_CENTROSCOS_ACT_ECON`
    FOREIGN KEY (`PF_EMP_ACE_EMPRESA` , `FK_CEN_ACE_CENTRO_COSTO` , `FK_CEN_ACE_SUB_CENTRO_COSTO`)
    REFERENCES `sysfrye_conta`.`con_centros_costos` (`PF_EMP_CEN_EMPRESA` , `PK_CEN_CENTRO_COSTO` , `PK_CEN_SUB_CENTRO_COSTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_EMPRESA_ACT_ECON`
    FOREIGN KEY (`PF_EMP_ACE_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INV_ACTIVIDAD_ECONOMICA_INV_SECTORES1`
    FOREIGN KEY (`PF_EMP_ACE_EMPRESA` , `FK_SEC_ACE_SECTOR`)
    REFERENCES `sysfrye_inve`.`inv_sectores` (`PF_EMP_SEC_EMPRESA` , `PK_SEC_CODIGO_SECTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_vendedores` (
  `PF_EMP_VEN_EMPRESA` INT(11) NOT NULL,
  `PK_VEN_CODIGO_VENDEDOR` INT(11) NOT NULL,
  `FK_NIT_VEN_NIT` VARCHAR(15) NULL DEFAULT NULL,
  `FK_MUL_VEN_CANALES` INT(11) NULL DEFAULT NULL,
  `VEN_CODIGO_TABLA` INT(11) NULL DEFAULT NULL,
  `VEN_TIPO_COMISION` INT(11) NULL DEFAULT NULL,
  `VEN_PORC_COMISION` FLOAT NULL DEFAULT NULL,
  `VEN_IMPRIME_COMISION` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PF_EMP_VEN_EMPRESA`, `PK_VEN_CODIGO_VENDEDOR`),
  INDEX `FK_MULTI_VENDEDORES` (`FK_MUL_VEN_CANALES` ASC),
  INDEX `FK_NITS_VENDEDORES` (`FK_NIT_VEN_NIT` ASC),
  CONSTRAINT `FK_EMPRESA_VENDEDORES`
    FOREIGN KEY (`PF_EMP_VEN_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_VENDEDORES`
    FOREIGN KEY (`FK_MUL_VEN_CANALES`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_NITS_VENDEDORES`
    FOREIGN KEY (`FK_NIT_VEN_NIT`)
    REFERENCES `sysfrye_conta`.`con_nits` (`PK_NIT_NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_zona_comercial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_zona_comercial` (
  `PF_EMP_ZOC_EMPRESA` INT(11) NOT NULL,
  `PK_ZOC_COD_ZONA` INT(11) NOT NULL AUTO_INCREMENT,
  `ZOC_DEPARTAMENTO` VARCHAR(3) NULL DEFAULT NULL,
  `ZOC_CIUDAD` VARCHAR(3) NULL DEFAULT NULL,
  `ZOC_DESCRIPCION` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_ZOC_COD_ZONA`, `PF_EMP_ZOC_EMPRESA`),
  INDEX `FK_EMPRESA_ZONACIAL` (`PF_EMP_ZOC_EMPRESA` ASC),
  CONSTRAINT `FK_EMPRESA_ZONACIAL`
    FOREIGN KEY (`PF_EMP_ZOC_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_clientes` (
  `PF_EMP_CLI_EMPRESA` INT(11) NOT NULL,
  `PK_CLI_CODIGO_CLIENTE` INT(11) NOT NULL,
  `FK_NIT_CLI_NIT` VARCHAR(15) NOT NULL,
  `FK_UBI_CLI_COD_UBICACION` INT(11) NOT NULL,
  `FK_ZOC_CLI_COD_ZONA_COMERCIAL` INT(11) NOT NULL,
  `FK_VEN_CLI_CODIGO_VENDEDOR` INT(11) NOT NULL,
  `FK_ACT_CLI_ACTIVIDAD_ECONOMICA` INT(11) NOT NULL,
  `FK_MUL_CLI_ESTADO` INT(11) NOT NULL,
  `FK_MUL_CLI_CANALES` INT(11) NOT NULL,
  `AF_LIS_CLI_LISTA` INT(11) NOT NULL,
  `CLI_NOMBRE_CLIENTE` VARCHAR(100) NULL DEFAULT NULL,
  `CLI_DIRECCION` VARCHAR(200) NULL DEFAULT NULL,
  `CLI_TELEFONO` VARCHAR(15) NULL DEFAULT NULL,
  `CLI_CUPO` INT(11) NULL DEFAULT NULL,
  `CLI_RETENCION_ICA` VARCHAR(1) NULL DEFAULT NULL,
  `CLI_AGENTE_RETENEDOR_IVA` VARCHAR(1) NULL DEFAULT NULL,
  `CLI_RETENCION_FUENTE` VARCHAR(1) NULL DEFAULT NULL,
  `CLI_PLAZO` INT(11) NULL DEFAULT NULL,
  `CLI_CREACION` DATE NULL DEFAULT NULL,
  `CLI_IDEXTRANJERO` VARCHAR(12) NULL DEFAULT NULL,
  `CLI_DIAS_RECAUDO` INT(11) NULL DEFAULT NULL,
  `CLI_LOCALIDAD` INT(11) NULL DEFAULT NULL,
  `CLI_DIAS_BLOQUEO` INT(11) NULL DEFAULT NULL,
  `CLI_BLOQUEADO` VARCHAR(1) NULL DEFAULT NULL,
  `CLI_FECHA_DOCUMENTACION` DATE NULL DEFAULT NULL,
  `CLI_FECHA_ACT_DOCUMENTOS` DATE NULL DEFAULT NULL,
  `CLI_DESCUENTO_FINANCIERO` FLOAT NULL DEFAULT NULL,
  `CLI_EXCLUIDO_IVA` VARCHAR(1) NULL DEFAULT NULL,
  `CLI_NOMBRE_CONTACTO` VARCHAR(200) NULL DEFAULT NULL,
  `CLI_TELEFONO_CONTACTO` VARCHAR(15) NULL DEFAULT NULL,
  `CLI_CARGO_CONTACTO` VARCHAR(50) NULL DEFAULT NULL,
  `CLI_CORREO_CONTACTO` VARCHAR(200) NULL DEFAULT NULL,
  `CLI_OBSERVACION` VARCHAR(200) NULL DEFAULT NULL,
  `CLI_LATITUD` FLOAT NULL DEFAULT NULL,
  `CLI_LONGITUD` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`PF_EMP_CLI_EMPRESA`, `PK_CLI_CODIGO_CLIENTE`),
  INDEX `fk_INV_CLIENTES_INV_ZONA_COMERCIAL1_idx` (`FK_ZOC_CLI_COD_ZONA_COMERCIAL` ASC),
  INDEX `fk_INV_CLIENTES_INV_VENDEDORES1_idx` (`PF_EMP_CLI_EMPRESA` ASC, `FK_VEN_CLI_CODIGO_VENDEDOR` ASC),
  INDEX `FK_NITS_CLIENTES` (`FK_NIT_CLI_NIT` ASC),
  INDEX `FK_MULTI_ESTADOCLIENTES` (`FK_MUL_CLI_ESTADO` ASC),
  INDEX `FK_MULTI_CANALCLIENTES` (`FK_MUL_CLI_CANALES` ASC),
  INDEX `fk_INV_CLIENTES_INV_ACTIVIDAD_ECONOMICA1_idx` (`FK_ACT_CLI_ACTIVIDAD_ECONOMICA` ASC, `PF_EMP_CLI_EMPRESA` ASC),
  INDEX `FK_UBICACION_CLIENTES` (`FK_UBI_CLI_COD_UBICACION` ASC),
  CONSTRAINT `FK_EMPRESA_CLIENTES`
    FOREIGN KEY (`PF_EMP_CLI_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_CANALCLIENTES`
    FOREIGN KEY (`FK_MUL_CLI_CANALES`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_ESTADOCLIENTES`
    FOREIGN KEY (`FK_MUL_CLI_ESTADO`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_NITS_CLIENTES`
    FOREIGN KEY (`FK_NIT_CLI_NIT`)
    REFERENCES `sysfrye_conta`.`con_nits` (`PK_NIT_NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UBICACION_CLIENTES`
    FOREIGN KEY (`FK_UBI_CLI_COD_UBICACION`)
    REFERENCES `sysfrye_global`.`glb_ubicacion` (`PK_UBI_COD_UBICACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INV_CLIENTES_INV_ACTIVIDAD_ECONOMICA1`
    FOREIGN KEY (`FK_ACT_CLI_ACTIVIDAD_ECONOMICA` , `PF_EMP_CLI_EMPRESA`)
    REFERENCES `sysfrye_inve`.`inv_actividad_economica` (`PK_ACE_CODIGO_ACTIVIDAD` , `PF_EMP_ACE_EMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INV_CLIENTES_INV_VENDEDORES1`
    FOREIGN KEY (`PF_EMP_CLI_EMPRESA` , `FK_VEN_CLI_CODIGO_VENDEDOR`)
    REFERENCES `sysfrye_inve`.`inv_vendedores` (`PF_EMP_VEN_EMPRESA` , `PK_VEN_CODIGO_VENDEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INV_CLIENTES_INV_ZONA_COMERCIAL1`
    FOREIGN KEY (`FK_ZOC_CLI_COD_ZONA_COMERCIAL`)
    REFERENCES `sysfrye_inve`.`inv_zona_comercial` (`PK_ZOC_COD_ZONA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_cabeza_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_cabeza_pedidos` (
  `PF_EMP_CAP_EMPRESA` INT(11) NOT NULL,
  `PK_TID_TIPO_NUMERACION` INT(11) NOT NULL,
  `PK_TID_CAP_NRO_DCTO` INT(11) NOT NULL,
  `FK_CLI_CAP_CODIGO_CLIENTE` INT(11) NOT NULL,
  `FK_MON_CAP_TIPO_MONEDA` INT(11) NOT NULL,
  `CAP_USUARIO` VARCHAR(15) NOT NULL,
  `CAP_FECHA_DCTO` DATETIME NOT NULL,
  `AF_CLI_CAP_UBICACION` INT(11) NOT NULL,
  `AF_CLI_CAP_ZONA` INT(11) NOT NULL,
  `AF_CLI_CAP_CODIGO_VENDEDOR` INT(11) NOT NULL,
  `AF_CLI_CAP_PLAZO_CLIENTE` INT(11) NOT NULL,
  `CAP_PLAZO_2` INT(11) NOT NULL,
  `CAP_PLAZO_3` INT(11) NOT NULL,
  `CAP_PLAZO_4` INT(11) NOT NULL,
  `CAP_POR_DESC_2` VARCHAR(3) NOT NULL,
  `CAP_POR_DESC_3` VARCHAR(3) NOT NULL,
  `CAP_VALOR_SUBTOTAL` FLOAT NOT NULL,
  `CAP_VALOR_DSCTO` FLOAT NOT NULL,
  `CAP_VALOR_FLETES` FLOAT NOT NULL,
  `CAP_VALOR_IVA` FLOAT NOT NULL,
  `CAP_TOTAL_PAGAR` FLOAT NOT NULL,
  `CAP_VALOR_RETENCION` FLOAT NOT NULL,
  `CAP_LEY_33` FLOAT NOT NULL,
  `CAP_LICITACION` VARCHAR(1) NOT NULL,
  `CAP_CON_DEVOLUCION` VARCHAR(1) NOT NULL,
  `CAP_VALOR_ICA` INT(11) NOT NULL,
  `CAP_VALOR_RETENEDOR_IVA` INT(11) NOT NULL,
  `CAP_PEDIDO_FACTURA` INT(11) NOT NULL,
  `CAP_ANULADA` VARCHAR(1) NOT NULL,
  `CAP_FECHA_ALTERA` INT(11) NOT NULL,
  `CAP_ESTADO_ALTERA` VARCHAR(1) NOT NULL,
  `CAP_RETENCION_SERVI` INT(11) NOT NULL,
  `CAP_DIRECCION_DESTINO` VARCHAR(100) NOT NULL,
  `CAP_ORDEN_CLIENTE` VARCHAR(20) NOT NULL,
  `CAP_VALOR_MONEDA` FLOAT NOT NULL,
  `CAP_REMISION` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`PF_EMP_CAP_EMPRESA`, `PK_TID_TIPO_NUMERACION`, `PK_TID_CAP_NRO_DCTO`),
  INDEX `fk_INV_CABEZA_FACTURAS_INV_CLIENTES1_idx` (`PF_EMP_CAP_EMPRESA` ASC, `FK_CLI_CAP_CODIGO_CLIENTE` ASC),
  CONSTRAINT `FK_EMPRESAS_CABEZAPEDIDO`
    FOREIGN KEY (`PF_EMP_CAP_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INV_CABEZA_FACTURAS_INV_CLIENTES1`
    FOREIGN KEY (`PF_EMP_CAP_EMPRESA` , `FK_CLI_CAP_CODIGO_CLIENTE`)
    REFERENCES `sysfrye_inve`.`inv_clientes` (`PF_EMP_CLI_EMPRESA` , `PK_CLI_CODIGO_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_combos_detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_combos_detalles` (
  `PF_MUL_ID_COMBO` INT(11) NOT NULL,
  `FK_ITE_COM_CODIGO_ITEM` VARCHAR(8) NOT NULL,
  `COM_PORCENTAJE` FLOAT NOT NULL,
  `COM_VALOR` FLOAT NOT NULL,
  PRIMARY KEY (`PF_MUL_ID_COMBO`, `FK_ITE_COM_CODIGO_ITEM`),
  INDEX `fk_INV_COMBOS_INV_ITEMS1_idx` (`FK_ITE_COM_CODIGO_ITEM` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_lineas_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_lineas_items` (
  `PF_EMP_LIN_EMPRESA` INT(11) NOT NULL,
  `PK_LIN_CODIGO_LINEA` INT(11) NOT NULL,
  `LIN_NOMBRE_LINEA` VARCHAR(50) NOT NULL,
  `LIN_CTA_INGRESOS` VARCHAR(12) NOT NULL,
  `LIN_CTA_IVA` VARCHAR(12) NOT NULL,
  `LIN_CTA_LEY_33` VARCHAR(12) NOT NULL,
  `LIN_CTA_RTE_ICA` VARCHAR(12) NOT NULL,
  `LIN_CTA_RTE_IVA` VARCHAR(12) NOT NULL,
  `LIN_CTA_FLETES` VARCHAR(12) NOT NULL,
  `LIN_CTA_RTEFTE` VARCHAR(12) NOT NULL,
  `LIN_CTA_DEUDORES` VARCHAR(12) NOT NULL,
  `LIN_CTA_DSCTO` VARCHAR(12) NOT NULL,
  `LIN_CTA_RTE_SER` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`PF_EMP_LIN_EMPRESA`, `PK_LIN_CODIGO_LINEA`),
  CONSTRAINT `FK_EMPRESAS_LINEAS`
    FOREIGN KEY (`PF_EMP_LIN_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_proveedores` (
  `PF_EMP_PRO_EMPRESA` INT(11) NOT NULL,
  `PK_PRO_CODIGO_PROVEEDOR` INT(11) NOT NULL,
  `FK_NIT_PRO_NIT` VARCHAR(15) NOT NULL,
  `FK_UBI_PRO_COD_UBICACION` INT(11) NOT NULL,
  `FK_MUL_PRO_TIPO_PROVEEDOR` INT(11) NOT NULL,
  `PRO_NOMBRE_PROVEEDOR` VARCHAR(100) NOT NULL,
  `PRO_DIRECCION` VARCHAR(100) NOT NULL,
  `PRO_TELEFONO` VARCHAR(20) NOT NULL,
  `PRO_CORREO_ELECTRONICO` VARCHAR(150) NULL DEFAULT NULL,
  `PRO_CUPO` FLOAT NULL DEFAULT NULL,
  `PRO_ES_RETE_FUENTE` VARCHAR(1) NULL DEFAULT NULL,
  `PRO_ES_RETE_IVA` VARCHAR(1) NULL DEFAULT NULL,
  `PRO_PLAZO_PAGO` INT(11) NULL DEFAULT NULL,
  `PRO_PORCENTAJE` FLOAT NULL DEFAULT NULL,
  `PRO_NOMBRE_CONTACTO` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`PF_EMP_PRO_EMPRESA`, `PK_PRO_CODIGO_PROVEEDOR`),
  INDEX `FK_NIT_PROVEEDORES` (`FK_NIT_PRO_NIT` ASC),
  INDEX `FK_UBICACION_PROVEEDORES` (`FK_UBI_PRO_COD_UBICACION` ASC),
  INDEX `FK_MULTI_TIPO_PROVEEDORES` (`FK_MUL_PRO_TIPO_PROVEEDOR` ASC),
  CONSTRAINT `FK_EMPRESAS_PROVEEDORES`
    FOREIGN KEY (`PF_EMP_PRO_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_TIPO_PROVEEDORES`
    FOREIGN KEY (`FK_MUL_PRO_TIPO_PROVEEDOR`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_NIT_PROVEEDORES`
    FOREIGN KEY (`FK_NIT_PRO_NIT`)
    REFERENCES `sysfrye_conta`.`con_nits` (`PK_NIT_NIT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_UBICACION_PROVEEDORES`
    FOREIGN KEY (`FK_UBI_PRO_COD_UBICACION`)
    REFERENCES `sysfrye_global`.`glb_ubicacion` (`PK_UBI_COD_UBICACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_items` (
  `PF_EMP_ITE_EMPRESA` INT(11) NOT NULL,
  `PK_ITE_CODIGO` VARCHAR(8) NOT NULL,
  `FK_PRO_ITE_CODIGO_PROVEEDOR` INT(11) NOT NULL,
  `FK_LIN_ITE_LINEA` INT(11) NOT NULL,
  `FK_MUL_ITE_COD_COMBO` INT(11) NULL DEFAULT NULL,
  `FK_MUL_ITE_UNIDAD_MEDIDA` INT(11) NOT NULL,
  `FK_MUL_ITE_SUBLINEA` INT(11) NOT NULL,
  `FK_MUL_ITE_GRUPO` INT(11) NOT NULL,
  `FK_MUL_ITE_SUBGRUPO` INT(11) NOT NULL,
  `ITE_NOMBRE_ITEM` VARCHAR(100) NOT NULL,
  `ITE_FACTOR` FLOAT NOT NULL,
  `ITE_VALOR_VENTA` FLOAT NOT NULL,
  `ITE_STOCK_MINIMO` INT(11) NOT NULL,
  `ITE_PEDIDO_MINIMO` INT(11) NOT NULL,
  `ITE_STOCK_MAXIMO` INT(11) NOT NULL,
  `ITE_LED_TIME` INT(11) NOT NULL,
  `ITE_INVENTARIO_SEGURIDAD` FLOAT NOT NULL,
  `ITE_EMBALAJE` FLOAT NOT NULL,
  `ITE_CODIGO_EAN` VARCHAR(20) NOT NULL,
  `ITE_UNIDAD_DIAN` VARCHAR(3) NOT NULL,
  `ITE_VALOR_PPTO_1` FLOAT NULL DEFAULT NULL,
  `ITE_VALOR_PPTO_2` FLOAT NULL DEFAULT NULL,
  `ITE_VALOR_PPTO_3` FLOAT NULL DEFAULT NULL,
  `ITE_VALOR_PPTO_4` FLOAT NULL DEFAULT NULL,
  `ITE_COSTO_PPTO_1` FLOAT NULL DEFAULT NULL,
  `ITE_COSTO_PPTO_2` FLOAT NULL DEFAULT NULL,
  `ITE_COSTO_PPTO_3` FLOAT NULL DEFAULT NULL,
  `ITE_COSTO_PPTO_4` FLOAT NULL DEFAULT NULL,
  `ITE_MTR_PPTO_1` FLOAT NULL DEFAULT NULL,
  `ITE_MTR_PPTO_2` FLOAT NULL DEFAULT NULL,
  `ITE_MTR_PPTO_3` FLOAT NULL DEFAULT NULL,
  `ITE_MTR_PPTO_4` FLOAT NULL DEFAULT NULL,
  `ITE_PORC_COMIS_1` FLOAT NULL DEFAULT NULL,
  `ITE_PORC_COMIS_2` FLOAT NULL DEFAULT NULL,
  `ITE_PORC_COMIS_3` FLOAT NULL DEFAULT NULL,
  `ITE_PORC_COMIS_4` FLOAT NULL DEFAULT NULL,
  `ITE_COSTO_PESOS` FLOAT NULL DEFAULT NULL,
  `ITE_COSTO_DOLLAR` FLOAT NULL DEFAULT NULL,
  `ITE_NOMBRE_EXTERIOR` VARCHAR(100) NULL DEFAULT NULL,
  `ITE_UNIDAD_EN_ENGLISH` VARCHAR(7) NULL DEFAULT NULL,
  `ITE_IVA` FLOAT NULL DEFAULT NULL,
  `ITE_PESO_UNITARIO` FLOAT NULL DEFAULT NULL,
  `ITE_PORCENTAJE_PRE` FLOAT NULL DEFAULT NULL,
  `ITE_ES_DESACTIVADO` VARCHAR(1) NULL DEFAULT NULL,
  `ITE_ES_IMPORTADO` VARCHAR(1) NULL DEFAULT NULL,
  `ITE_ES_SERVICIO` VARCHAR(1) NULL DEFAULT NULL,
  `ITE_ES_PRODUCCION` VARCHAR(1) NULL DEFAULT NULL,
  `ITE_ES_TERMINADO` VARCHAR(1) NULL DEFAULT NULL,
  `ITE_ES_SEMIELABOR` VARCHAR(1) NULL DEFAULT NULL,
  `ITE_ES_SINCOSTO` VARCHAR(1) NULL DEFAULT NULL,
  `ITE_ES_COMBO` VARCHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`PF_EMP_ITE_EMPRESA`, `PK_ITE_CODIGO`),
  INDEX `fk_INV_ITEMS_INV_PROVEEDORES1_idx` (`PF_EMP_ITE_EMPRESA` ASC, `FK_PRO_ITE_CODIGO_PROVEEDOR` ASC),
  INDEX `fk_INV_ITEMS_INV_LINEAS_ITEMS1_idx` (`FK_LIN_ITE_LINEA` ASC),
  INDEX `fk_INV_ITEMS_INV_LINEAS_ITEMS1` (`PF_EMP_ITE_EMPRESA` ASC, `FK_LIN_ITE_LINEA` ASC),
  INDEX `FK_MULTI_CODCOMBOS` (`FK_MUL_ITE_COD_COMBO` ASC),
  INDEX `FK_MULTI_UNIDAD_MEDIDA` (`FK_MUL_ITE_UNIDAD_MEDIDA` ASC),
  INDEX `FK_MULTI_SUBLINEA` (`FK_MUL_ITE_SUBLINEA` ASC),
  INDEX `FK_MULTI_GRUPO` (`FK_MUL_ITE_GRUPO` ASC),
  INDEX `FK_MULTI_SUBGRUPO` (`FK_MUL_ITE_SUBGRUPO` ASC),
  CONSTRAINT `FK_EMPRESAS_ITEMS`
    FOREIGN KEY (`PF_EMP_ITE_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_CODCOMBOS`
    FOREIGN KEY (`FK_MUL_ITE_COD_COMBO`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_GRUPO`
    FOREIGN KEY (`FK_MUL_ITE_GRUPO`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_SUBGRUPO`
    FOREIGN KEY (`FK_MUL_ITE_SUBGRUPO`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_SUBLINEA`
    FOREIGN KEY (`FK_MUL_ITE_SUBLINEA`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_UNIDAD_MEDIDA`
    FOREIGN KEY (`FK_MUL_ITE_UNIDAD_MEDIDA`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INV_ITEMS_INV_LINEAS_ITEMS1`
    FOREIGN KEY (`PF_EMP_ITE_EMPRESA` , `FK_LIN_ITE_LINEA`)
    REFERENCES `sysfrye_inve`.`inv_lineas_items` (`PF_EMP_LIN_EMPRESA` , `PK_LIN_CODIGO_LINEA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INV_ITEMS_INV_PROVEEDORES1`
    FOREIGN KEY (`PF_EMP_ITE_EMPRESA` , `FK_PRO_ITE_CODIGO_PROVEEDOR`)
    REFERENCES `sysfrye_inve`.`inv_proveedores` (`PF_EMP_PRO_EMPRESA` , `PK_PRO_CODIGO_PROVEEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_lista_precios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_lista_precios` (
  `PF_EMP_LIS_EMPRESA` INT(11) NOT NULL,
  `PK_LIS_COD_LISTA` INT(11) NOT NULL,
  `PF_ITE_LIS_ITEM` VARCHAR(8) NOT NULL,
  `LIS_NOMBRE_LISTA` VARCHAR(50) NOT NULL,
  `LIS_VALOR` FLOAT NOT NULL,
  PRIMARY KEY (`PF_EMP_LIS_EMPRESA`, `PK_LIS_COD_LISTA`, `PF_ITE_LIS_ITEM`),
  CONSTRAINT `FK_EMPRESA_LISTA_PRECIOS`
    FOREIGN KEY (`PF_EMP_LIS_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sysfrye_inve`.`inv_tipos_movimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sysfrye_inve`.`inv_tipos_movimientos` (
  `PF_EMP_TIM_EMPRESA` INT(11) NOT NULL,
  `PF_MUL_TIM_TIPO_NUMERACION` INT(11) NOT NULL,
  `PK_TIM_TIPO_DOCUMENTO` VARCHAR(3) NOT NULL,
  `TIM_CONSECUTIVO` INT(11) NOT NULL,
  `TIM_DESCRIPCION` VARCHAR(60) NOT NULL,
  `TIM_ES_FACTURA` VARCHAR(1) NOT NULL,
  `TIM_RESOLUCION` VARCHAR(20) NULL DEFAULT NULL,
  `TIM_FECHA_INI_RESOLUCION` DATE NULL DEFAULT NULL,
  `TIM_FECHA_FIN_RESOLUCION` DATE NULL DEFAULT NULL,
  `TIM_PREFIJO` VARCHAR(5) NULL DEFAULT NULL,
  `TIM_DESDE` INT(11) NULL DEFAULT NULL,
  `TIM_HASTA` INT(11) NULL DEFAULT NULL,
  `TIM_AFECTA_CARTERA` VARCHAR(1) NULL DEFAULT NULL,
  `TIM_URL_IMAGEN` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`PF_EMP_TIM_EMPRESA`, `PF_MUL_TIM_TIPO_NUMERACION`, `PK_TIM_TIPO_DOCUMENTO`),
  INDEX `FK_MULTI_TIPODOC` (`PF_MUL_TIM_TIPO_NUMERACION` ASC),
  CONSTRAINT `FK_EMPRESAS_TIPODOC`
    FOREIGN KEY (`PF_EMP_TIM_EMPRESA`)
    REFERENCES `sysfrye_global`.`glb_empresas` (`PK_EMP_CODEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_MULTI_TIPODOC`
    FOREIGN KEY (`PF_MUL_TIM_TIPO_NUMERACION`)
    REFERENCES `sysfrye_global`.`glb_multitabla` (`PK_MUL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;